version: 0.0
os: linux

files:
  - source: deploy.sh
    destination: /opt/node-app
    overwrite: yes
  - source: .
    destination: /opt/node-app
    overwrite: yes

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: root
