version: 0.0
os: linux

# Only copy artifact files (like appspec.yml and any scripts) to EC2
files:
  - source: /
    destination: /opt/node-app
    overwrite: yes

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: root
